server:
  port: 1235

spring:
  jackson:
    parser:
      ALLOW_NON_NUMERIC_NUMBERS: true

logging:
  level:
    org.springframework.web: INFO
    com.sensors.server: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

influxDb:
  url: "http://localhost:8086"
  database: "gauges"